const countries = {
  "ar-SA": "Arabic",
  "bn-IN": "Bengali",
  "de-DE": "German",
  "dv-MV": "Maldivian",
  "el-GR": "Greek",
  "en-GB": "English",
  "es-ES": "Spanish",
  "fr-FR": "French",
  "gu-IN": "Gujarati",
  "hi-IN": "Hindi",
  "it-IT": "Italian",
  "ja-JP": "Japanese",
  "kn-IN": "Kannada",
  "ko-KR": "Korean",
  "la-VA": "Latin",
  "ne-NP": "Nepali",
  "nl-NL": "Dutch",
  "pa-IN": "Panjabi",
  "pt-PT": "Portuguese",
  "ru-RU": "Russian",
  "sr-RS": "Serbian",
  "sv-SE": "Swedish",
  "ta-LK": "Tamil",
  "te-IN": "Telugu",
  "tr-TR": "Turkish",
  "ur-PK": "Urdu",
};
